### PR TITLE
Added SMAA_CG mode for compiling with NVIDIA CG Toolkit

### PR DESCRIPTION
**Pull request by ghost**
Luckily it was only a few lines thanks to your defines !

Note that despite my commit message, I have tested it now. It compiles on OpenGL using profiles arbfp/arbvp1 and up.

### CODE REVIEW

**Comment by ghost** [comment]
Discovered a few issues, closing until then.

**Comment by ghost** [comment]
Reopening, works now. Just make sure to use a SM3+ profile.

**Comment by iryoku** [comment]
I'd love to have a way to test if CG compiles; I'm sure it does right now, but if further development is done, having a programmatically way to at least check if it compiles would be very useful.

Could you please put a CG shader in /Scripts/TestCG with three different entry points, one for each pass, and three bat files that call cgc (http://http.developer.nvidia.com/Cg/cgc.html) for checking compilation problems?

Thanks!

**Comment by ghost** [comment]
Sorry I have lost interest in CG, I think it is a dead end now, so gonna close this pull request.

**Pull request closed without merging**
